### ISSUE TITLE
make install should not invoke compiler if not strictly necessary

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#107]
The way "make install" currently work is:
1. Compile a new file src/config/ConfigInstall.o which contains hardcoded paths to install directory
2. Link the object files, including the new one, directly on the install directory

The reason for this is to allow users to specify the install location just before typing "make install". However, using "./configure" the standard way to specify the install location is with "./configure --prefix" so that install path is known at compilation time. It would be relatively easy to compile the ConfigInstall.o file and the link the final version of the library during the initial compilation. Then, "make install" should redo the job only if necessary because the path was changed in the meanwhile.

This would allow to use:
./configure --prefix=/xxx
make
sudo make install
In systems where root user does not have access to the compilers.

I will do it with low priority

Giovanni

**Comment by carlocamilloni** [comment]
@plumed/all 
Today Max and I met  a problem related to this. We have installed plumed on a pc and then we have copied the installed version of plumed to a new pc thinking that it would have worked. This was not the case unfortunately (for the tools at least, the library was actually working) because of the hardcoded path to the patches. Why cannot we just read the path in a way in which first plumed look for an enviroment variable, if the variable is not set then it looks in ../patches with respect to the folder where plumed executable is and only at last it gives an error. Furthermore why should it give an error if we are not using plumed patch?

Later today I found out that by using --standalone-executable it is possible to get around this problem, but I have to say that is not very intuitive

**Comment by GiovanniBussi** [comment]
@carlocamilloni I think you refer to a problem that is not related to this issue. This issue (#107) is about the need for compilers to be in the path when you type "make install". Your comment is about plumed patches to be in the correct hardcoded path when your type "plumed driver". I will copy your message to another thread

**Comment by GiovanniBussi** [comment]
This issue has been fixed in v2.2
