### ISSUE TITLE
Possible bug in Multiple Walkers

### ISSUE THREAD

**Issue by davidebr** [plumed/plumed2#119]
Paolo Raiteri reported some strange behaviour in the MWs: they seem not to synchronize properly.
I've not understood properly what is the issue but might be connected with buffering. Possible solutions might be to flush the HILLS file at every hills (or, every WALKERS_RSTRIDE if we do not want to overload the filesystem) forcibly whenever the MW are activated. 
An improvement recommended is also to remove the restart condition from the constructor: if the file exists, then assume that is right and use it (as a matter of fact MWs are always like restarting the metad at every time)

**Comment by GiovanniBussi** [comment]
I think this bug in sync has been fixed in 26152b244505221b3257de6e8e651acf42f057bf (to be 2.2.5 and 2.3.1), so I close this issue. About removing RESTART option I am not sure it is a good idea. Also, this is very specific for multiple-walkers, in other cases I think the present behavior is more consistent (files are appended upon restart, backupped otherwise).
