### ISSUE TITLE
MOLINFO with protein/rna complexes

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#133]
I just pushed on master an implementation of special symbols for rna and dna. They work properly. Not only backbone angles are defined, but also many other useful names (e.g. sugar, base, ...).

However, I am not satisfied with the fact that one should specify the MOLINFO type in the input. This makes it difficult to load names for a rna/protein complex.

An additional problem is that if there are multiple chains (and thus repeated res number) plumed will only interpret the first occurrence.

**Comment by carlocamilloni** [comment]
as a work around to the protein/rna case one can use multiple MOLINFO keyword one for each molecule type. The chain issue should be solved, but in the meantime it would be probably useful to give an error if multiple residues have the same number and suggest to renumber the residues in the pdb.

**Comment by GiovanniBussi** [comment]
@carlocamilloni to fix this I had to make an extensive rewrite of the specialSymbol stuff. Can you double check if what I did on branch fix-133 (e2bf7aea4ee311897508e64054e16bc1990ad429) is correct before I merge on master branch? Thanks!

First issue (protein/rna/dna): any of the three works equivalently, and all residue type are recognized. This should be fine since e.g. ALA is always protein and DG is always DNA

Second issue (chain id): I implemented the possibility to use phi-A3 (residue 3 of chain A). Do you think this syntax is ok?

**Comment by carlocamilloni** [comment]
@GiovanniBussi I am checking it tomorrow. For the chain-residue selection I don't know, I will test it with some problematic case

**Comment by carlocamilloni** [comment]
@GiovanniBussi it works. One problem I see is instead with the "setup action". Recently from the PDB it is not possible anymore to download one single file for large PDB complexes like the ribosome, instead one can download multiple pdbs with subsets of chains, in this way the syntax is more standard, for example in the past one could have chain ID with numbers or with two characters, but now the problem is that it is not possible in plumed to do something like:

MOLINFO STRUCTURE=chain-a.pdb
cv1: TORSION ATOMS=@alpha-A7

MOLINFO STRUCTURE=chain-a2.pdb
cv2: TORSION ATOMS=@alpha-A2

MOLINFO STRUCTURE=chain-a3.pdb
cv3: TORSION ATOMS=@phi-A3

So, I think that we can merge this, but we should consider changing the code in the future to allow for the above behaviour.

**Comment by GiovanniBussi** [comment]
Thanks @carlocamilloni !
I merged this on master and opened a new issue on the problem related to multiple PDBs (#134)
