### ISSUE TITLE
Make install tries to install docs but doesn't trigger make doc

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#136]
I have just noticed that when doing make install we try to install:

tar: *-doc/html: Cannot stat: No such file or directory
tar: *-doc/regtests: Cannot stat: No such file or directory
tar: *-doc/manual.pdf: Cannot stat: No such file or directory

I think this is bug. If we want PLUMED to install docs and retests we should trigger their compilation,
alternatively we can remove that tar command.

In my opinion we should install the documentation but not the regtests.

**Comment by GiovanniBussi** [comment]
I think we should just ignore the error (maybe change makefile so that it is not reported).
In many cases people don't want their own manual installed, or they do not have doxygen.

**Comment by carlocamilloni** [comment]
I would remove the installation of the docs from make install and add a method install-doc then, do you agree?

**Comment by GiovanniBussi** [comment]
I would prefer leaving it as is since in our workstations I install a local version of the manual (with our additional features) and I am 100% sure at one point I will forget to do install-doc... Also, the GNU standard (www.gnu.org/prep/standards/html_node/Standard-Targets.html) seems to be that documentation (info file, in that case) is installed with "make install". They allow optionally other formats ("make install-pdf" etc).

For us maybe it could only make sense to split user-doc and developer-doc. That is, with "make install" only install used-doc. But I do not know if it is worthwhile. Plus there will be links not working in the user doc.

**Comment by carlocamilloni** [comment]
Ok, yes I don't think it is worth spending more time on this ;-)
