### ISSUE TITLE
Tools to automatically build path CVs

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#150]

**Comment by tonigi** [comment]
Not sure if it's what you meant, but PLUMED-GUI has [Structure>Build Reference Structure](https://github.com/tonigi/vmd_plumed/tree/master/doc#reference-structures-for-rmsd-and-path-variables), which also builds paths.

**Comment by gtribello** [comment]
Hello @GiovanniBussi 

I just added a branch (pathtools) that creates paths in two ways.  

(1)  It takes a bunch of non-equally-spaced frames and makes them all equally spaced.

(2)  It takes in a start point and an end point and create a set of frames along the vector connecting these two frames.

I wrote similar stuff while I was visiting Bernd and thus figured it might be useful for others to have this.  I haven't got any regtests for this at the moment as I didn't want to modify all the regtest stuff so that I can add stuff to test by running this cltool.  I wanted to check how to do this first. 

Thanks
Gareth

**Comment by GiovanniBussi** [comment]
Hi @gtribello 

This is very useful!

If you need a regtest for a different cltool you can just use
type=plumed
arg="pathtools options"

See e.g. basic/rt-hrex-0/config in master branch

Giovanni

**Comment by gtribello** [comment]
Hello @GiovanniBussi 

Thanks for this advice.  I have created the regtsts and put the in the pathtools branch.  The problem is that I get a segfault whenever I try to run some of the tests using make.  I don't know what is going on as when I run the same test using just the regular commands they work fine.  That is to say the commands run fine when I run the tests without all the regtest machinery.  Also I created four tests and two of them work perfectly.

I also tried putting an abort before the pathtools code finishes and the segfault doesn't appear in this case either.  I am at a bit of a loss here so I was wondering if you could take a look and help out.

The tests in question are on the pathtools branch on the origin and in the directories:

rt-pathtools-1
rt-pathtools-2

Thanks
Gareth

**Comment by GiovanniBussi** [comment]
@gtribello Is this working now? I cannot reproduce the problemi

**Comment by gtribello** [comment]
@GiovanniBussi yes sorry I should have said I fixed it using the magic of valgrind :-)

**Comment by GiovanniBussi** [comment]
Hi @gtribello this issue can be closed now, correct? Thanks!

**Comment by gtribello** [comment]
yes.  Thanks @GiovanniBussi

**Comment by GiovanniBussi** [comment]
Implemented in master branch (will be available in v2.4)
