### ISSUE TITLE
Add multiple basins for COMMITTOR

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#172]
I open an issue for this feature. It has been discussed in this commit: plumed/plumed2@58df0c3dd5

**Comment by carlocamilloni** [comment]
@GiovanniBussi @gtribello I have pushed a first modified version of the COMMIT analysis that should allow for the definition of multiple basins. It still needs some refinement and better docs I think. I kept the definition of both lower and upper limits because removing them would have made everything more complex. I think that it is always possible to provide such large limits that at the end of the day are just like setting a single boundary

**Comment by GiovanniBussi** [comment]
I agree that it is not necessary to have multiple boundaries.
@carlocamilloni can you check the manual? I think the syntax is not anymore compatible right? So we should also add a notice in the changelog that syntax is incompatible. Also, perhaps there is no regtest for this action (otherwise it would have failed with the change)
