### ISSUE TITLE
Enabling to have actions with two arguments or with arguments and parameters

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#176]
to have something like

cv1: DISTANCE
ene: RESTRAINT

ACTION ARG=cv1 ARG2=cv2 or even better
ACTION ARG=cv1 PARAM=ene.bias

where param is an argument transformed into a parameters using this: https://github.com/plumed/plumed2/commit/0f612125c15cfcb39bea3363a8fe6c63c5aecbbd

**Comment by GiovanniBussi** [comment]
I agree this would be useful.

A few comments:
- Two arguments: this should be relatively easy. requestAtoms() and requestArguments() are quite symmetric, so we can do the same thing that we do e.g. in COORDINATION to have two groups (GROUPA and GROUPB instead of ATOMS). Inside the action arguments will be numbered progressively (in your example argument 0 will be cv1 and argument 1 will be cv2). Let's just be careful in doing it in a way that does not require to rewrite the existing biases and functions.
- Arguments and Parameters: Isn't parameter just another value? Or there is something different that I don't understand?

As a side comment about the PARAMETER stuff, I think we have to be a bit careful. As far as I understand this is acting as a sink for forces (which are not propagated through). This is going to break energy conservation and perhaps introduce other undesired effects. So if we include this we have to put a big warning (such as those in POSITION etc) to avoid misuse. I actually would like to use something like this in analysis (where forces are not an issue) to stop the force propagation and allow reweighting on variables that do not have derivatives. But I think that using it in biased MD is a bit dangerous. Or perhaps I am missing something...

**Comment by maxbonomi** [comment]
More specifically, Carlo and I would like to calculate (using the function ENSEMBLE) the weighted average of a CV over a set of replicas of the system. The weight is a function of the bias, which is now passed as a PARAMETER to the ENSEMBLE keyword. But we are currently missing the derivative of the weight wrt the CV, as we could not access the derivative of the bias wrt the CV.

**Comment by carlocamilloni** [comment]
Actually we don't need to do anything for this. In STATS I implemented the possibility of taking arguments with derivatives in ARG and arguments without derivatives in PARARG. But it is also enough to not use the keyword ARG and just parse the ARGUMENTS in the way one prefer as for atoms.
