### ISSUE TITLE
Efficient Matrix operations?

### ISSUE THREAD

**Issue by jmichel80** [plumed/plumed2#184]
Dear developers,

I am looking for C++ code to perform matrix operations on large (a few hundred dimensions) rectangular matrices (specifically matrix multiplications, transposes, and matrix inversion). Efficiency is important as I want to perform matrix inversions at every MD timestep. 
I am wondering if any developer could recommend a sensible way to add this functionality to plumed 2?  

Best wishes, 

Julien

**Comment by GiovanniBussi** [comment]
Hi Julien, if you need to do that inside plumed the easiest choice is with blas/lapack.
Notice that in plumed they are always available, since when not installed they are replaced with an internal version.
Just include "tools/blas.h" or "tools/lapack.h" and use names such as:
plumed_lapack_dsyevr()

Giovanni

**Comment by jmichel80** [comment]
Hi Giovanni, 

Thanks that's very useful to know ! 

Best wishes, 

Julien
