### ISSUE TITLE
Bug in BRIDGE

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#185]
I found a nasty bug in BRIDGE.

Apparently, when there are more than ~ 1625 bridging atoms the code does a segfault.
I pushed a regtest right now (branch bug-bridge).

I tried to debug the code without success. Apparently there is a task code exceeding 2**32 (max value for an unsigned). This makes me fear that other multicolvars could be affected.

The regtest fails on travis, giving:
- out of boundary access with debug flags
- segfault in other cases

Notice that sometime on my mac the code ends without segfault but giving a wrong result for the calculation with more than 1625 atoms (this makes it a bit scaring).

**Comment by gtribello** [comment]
Hello @GiovanniBussi 

This is a flaw that I am aware of.  I would say its more a design flaw than a bug.  At the moment though it is only likely to affect the actions ANGLES, BRIDGE and INPLANEDISTANCES and only if you are using large numbers of atoms as you are here.  I am thinking about how to solve it off and on but I'm not happy with the ideas I have at the moment.  For the time being I can probably add some sort of check in order to make it at least crash with an error in the instances when the number of atoms is too high.  Can you send me an input so I can do so?

On the plus side I know how to solve the problem for BRIDGE and have done so.  Have a go at your calculation with the branch fix-185 and let me know how it goes.

**Comment by GiovanniBussi** [comment]
I classified it as a bug since it does not report any error or warning. Crashes are not given by asserts, but by (random and partly not reproducible) segfaults. On my mac I am able to complete the calculation with an erroneous result, which makes it dangerous. As a quick fix I an splitting the calculation in two groups, merging the result with COMBINE.

Anyway, the fix you made solves the problem with the regtest rt-waterbridge2 on my mac, I am waiting for the travis test now. Perhaps it is ok now? Questions:
- Why aren't you happy? Is there something that should be changed?
- Why with this change the result of one of the regtest rt-waterbridge is affected? Does it mean that the regtest was incorrect? Notice that I am speaking about the small regtest, with groups of 10 atoms.
- Is it possible to backport it to 2.2? In case not, we should at least at an error when someone asks too many atoms.

Thanks!

Giovanni

**Comment by gtribello** [comment]
@GiovanniBussi 

In answer to the three questions.  

The solution I would like to adopt for this is to have an error if someone uses too many atoms in these problematic cases.  This would mean adding an extra check in the code.  I have a complete solution to this problem that works specifically for BRIDGE and in another place where I have seen it come up.  These solutions work with what is calculated in those instances.  However, they won't work for ANGLES or INPLANEDISTANCES.  If it were required I could come up with solutions in those cases but I am not keen to unless someone specifically needs the functionality.

I can back port the change I made onto v2.2.  I would like to do it like this:

(1)  You send me an example input for the calculation that was crashing.
(2)  I modify the code so that it throws an error for this calculation.  This error would then appear if someone tries to do something similar.
(3)  I cherry-pick the commit I just made on fix-85 onto the code and thus fix BRIDGE.  This would not fix ANGLES and INPLANEDISTANCES but the error would be thrown if someone tried something similar.

The regtest wasn't incorrect and is still correct.  The issue is that the order of the atoms in the CV was changed and so the order in which the derivatives are output is changed.  I checked and if you take the old derivatives.reference file and reorder the atoms appropriately you see that the numbers are identical.

**Comment by GiovanniBussi** [comment]
this would be a great solution! You can find the test in branch bug-bridge, regtests/multicolvar/rt-warerbridge2.

For branch 2.2, if back porting is difficult I think it is sufficient to add the check.

Thanks again!

Giovanni 

Inviato da iPhone

**Comment by GiovanniBussi** [comment]
As a side note, I saw this uses linked cells. Should I expect it to work properly also with non orthorhombic cells? Giovanni

Inviato da iPhone

**Comment by gtribello** [comment]
OK it should now be fixed.  I had to change the plan slightly.  v2.2 now crashes if you do that test but it works on master.  The reason for this is that I used some code that is only in master and that I don't want to back port onto v2.2.  I also added the regtest that was in bug-bridge into master so if there is nothing else on that branch you can get rid of it.

As for the non-orthorhombic cells.  I have never tried.  I thought the way I had done it would work but after a conversation with you I am now not certain.  It also won't give an error if you try and run with a non-orthorhombic cell.  If you want to look into this and talk about it on Skype I should have time next week.

**Comment by GiovanniBussi** [comment]
I added a notice in the changelogs, I think we can consider this issue as closed.
