### ISSUE TITLE
log.printf and mpi

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#188]
There is a problem when using the OFile class (like doing log.printf) if this is not executed by all thread of a simulation due to a Bcast in llwrite. The code hang and it took me almost a week to find the reason. Is there a way to avoid the Bcast? In particular because the return value (r) seems to not be used.

**Comment by GiovanniBussi** [comment]
Hi,

all the operations in OFile and IFile are synchronizing all the processors of the group as of now.

I think you are right that this is not written anywhere, and should be written in the manual.
Anyway, I would only change it if it makes the code slower. I think the code is clearer in this way: all the calls to access the file system should be made in the non-parallelized part of the code. This is true for all open/close/read/write operations. Otherwise one might think that he can write information from processors different from root in the parallelized part.

Perhaps we should also write somewhere that Log file should not be used for debugging: stderr is the right thing (which allows you to write from all the processes).

What do you think?

Giovanni

**Comment by carlocamilloni** [comment]
Hi

@GiovanniBussi 
I don't think that this synchronisation has an impact on the performances, but if you print often (i.e. every step or so). In my case I was not using it for debugging, only using multi_sim.Get_size() inside a log.printf, and the two operations are not compatible, because the first can only be executed by master threads while the second should be executed by all threads... . From this point of view while on one hand I agree that the code is clearer in the present way on the other one could synchronise open/close operation and let the writing be asynchronous. At the same time I don't care too much about it, we can leave it as it is and document the behaviour in the manual.
