### ISSUE TITLE
documentation to use PLUMED with NAMD

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#227]
In the manual there is no indication about how to run a namd simulation with plumed, I think is probably trivial but for example I have never tried and today I have received an email in which the main problem was that the person was trying to run namd using -plumed plumed.dat

**Comment by GiovanniBussi** [comment]
@HanatoK since you are using NAMD maybe can you help us fixing this?

It's just matter of adding a sentence to [this file](https://github.com/plumed/plumed2/blob/master/patches/namd-2.9.config). If you tell me how you run NAMD I will add it.

In addition, I was wondering if you are aware of a more up to date NAMD patch that could be replaced.

Many thanks!

Giovanni

**Comment by HanatoK** [comment]
@GiovanniBussi 
Add the following lines in the NAMD configuration file (often named as xxx.namd or xxx.conf) and run the plumed-patched version of NAMD with it: 
```
plumed on
plumed plumed.dat
```
The first line tells NAMD to run with plumed and the second line specifies the plumed input file.
As far as I know @giacomofiorin has already made a patch for NAMD 2.12 in https://github.com/giacomofiorin/plumed2/tree/namd-updates

**Comment by HanatoK** [comment]
@GiovanniBussi 
I am sorry I have made a stupid mistake in the previous comment. The NAMD configuration should be:
```
plumed on
plumedfile plumed.dat
```
Could you correct the documentation accordingly?

**Comment by DearDeer7** [comment]
> 
Is there a difference between the plumed-patched version and the standard version of NAMD?  I add your two lines to the conf file while it tells me that "FATAL ERROR: ERROR(S) IN THE CONFIGURATION FILE". Could you give me further instructions or advice?

**Comment by GiovanniBussi** [comment]
> Is there a difference between the plumed-patched version and the standard version of NAMD

Yes. The former is patched. Did you patch NAMD? Otherwise the error you report is expected.

**Comment by DearDeer7** [comment]
I  tried to patch NAMD by `plumed patch -p` while I got an error "ERROR: Preliminary test not passed." (details in the figure below). Noted that I download NAMD release directly instead of compiling one myself. Is that OK?
![figure_20221115093016](https://user-images.githubusercontent.com/42965045/201804839-c1e79192-193a-4b70-8538-aed5edf20508.png)



> > Is there a difference between the plumed-patched version and the standard version of NAMD
> 
> Yes. The former is patched. Did you patch NAMD? Otherwise the error you report is expected.

**Comment by GiovanniBussi** [comment]
You should download the source code and compile it yourself
