### ISSUE TITLE
impact of sharing coordinates on the performances 

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#241]
see https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/plumed-users/M5M3XKBOLEU/R69T_PNMBwAJ

**Comment by carlocamilloni** [comment]
@plumed/all could you check the changes I made in the branch fix-241?
I think these will have a big impact when running large systems on many mpi threads.
There are still additional possible improvements:
- unique atoms should be updated only if it is the case instead than at every step (i.e. domain decomposition step or neighbour list step) this should be minor
- memory for position/charges/masses should be tuned to the maximum number of atoms needed by plumed and not to the atoms of the system

**Comment by carlocamilloni** [comment]
@plumed/all Hi, I made a few more changes to make it still a bit faster for most of the cases, in all the test I have done it is always faster than before so given also Max observation that for some compilers it can make a big difference I think we can merge it as a first step of optimisation. Any comment?

**Comment by GiovanniBussi** [comment]
@carlocamilloni can you upload the input files of the benchmarks on [this repo](https://github.com/plumed/benchmarks)? If I remember correctly they were very dummy tests, with no fancy variable computed (just distance), which is good since they would work across several plumed versions. We could even compare 2.2/2.3/2.4 and see how the performance is improving.

For now we can just store input files. It would be nice to make some nice graphical output so that people can add their own benchmark results (with a pull request on that repo) and we automatically plot graph on gh-pages branch. But this requires some work. Meanwhile, if you just share the input files, I can also try them on SISSA cluster

**Comment by maxbonomi** [comment]
I think having this benchmark is a very good idea.
I would try to identify a set of different compilers / versions and machines and report the output in all these different cases.

I could run the benchmark on a CRAY XC40 with multiple versions of gnu, intel, and cray compilers.
I think we should also identify a set of compiler options to test.

More specifically, I have access to the following versions of gnu, intel, and cray compilers.

gcc/4.7.2
gcc/4.7.3
gcc/4.8.0
gcc/4.8.1
gcc/4.8.2
gcc/4.9.0
gcc/4.9.1
gcc/4.9.2
gcc/4.9.3
gcc/5.1.0
gcc/5.2.0
gcc/5.3.0
gcc/6.1.0
gcc/6.2.0 

intel/15.0.7.235
intel/16.0.4.258
intel/17.0.1.132

cce/8.2.6
cce/8.3.11
cce/8.3.12
cce/8.3.14
cce/8.4.1
cce/8.4.3
cce/8.4.6
cce/8.5.6

Max

**Comment by carlocamilloni** [comment]
uploaded

**Comment by carlocamilloni** [comment]
I close this and open a "BENCHMARK issue"
