### ISSUE TITLE
CLtools issue in reading options

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#245]
I noticed that in driver if I use --initial-step or --time step as the last option one either gets an error message (i.e. --timestep 0.005) 

ERROR in input for command line tool driver : 0.005 option is unknown 

or the option is ignored

i.e. --timestep=0.005

the actual tilmestep is 1

**Comment by GiovanniBussi** [comment]
I just tried in `regtest/basic/rt0` to make this change:

````
diff --git a/regtest/basic/rt0/config b/regtest/basic/rt0/config
index 4804b7f2a..0b6952e66 100644
--- a/regtest/basic/rt0/config
+++ b/regtest/basic/rt0/config
@@ -1,4 +1,4 @@
 type=driver
 # this is to test a different name
-arg="--plumed plumed.dat --trajectory-stride 10 --timestep 0.005 --ixyz trajectory.xyz --dump-forces forces --dump-forces-fmt=%8.4f"
+arg="--plumed plumed.dat --trajectory-stride 10 --ixyz trajectory.xyz --dump-forces forces --dump-forces-fmt=%8.4f --timestep 0.005"
 extra_files="../../trajectories/trajectory.xyz"
````
that is I move the `--timestep` option to the end and it looks it is working, both with 2.3 and 2.4.

**Comment by carlocamilloni** [comment]
yes you are right, this happens only if you add something like --debug-dd, if you remove it it works, probably reading this hidden keywords trigger something weird

**Comment by GiovanniBussi** [comment]
I went back into this and the problem is that there is no way to have something like an "hidden flag". I mean, something that does not appear in the manual (=hidden) and that is a flag (=it does not consume the next command line argument). In this case, we are speaking about these driver flags:
````
--debug-dd
--debug-pd
--driver-float
````
Basically, even though they are supposed to be flags, they need one argument.

We have three options:

1. Allow hidden flags in keywords.
2. Make these three flags visible in the manual.
3. Make these three flags normal options with an argument (e.g. `--debug-dd yes`).

Unless @gtribello says that option 1 is easy to implement, I would go for options 2 or 3. Any preference? If not, I will draw a coin.

Giovanni

**Comment by carlocamilloni** [comment]
I would go for option 3 in case

Sent from my iPhone

**Comment by maxbonomi** [comment]
For me two or three are equally good

**Comment by gtribello** [comment]
I think the hidden flags are easy to implement.  There certainly is an option for doing hidden flags (flags that don't appear in the manual) in the keywords module as I have used them when writing Actions.  I just don't know if I included that functionality in the parse modules for cltools.  It should be easy to add though.

**Comment by gtribello** [comment]
Ah nope having read this more carefully it is more complicated than I thought.  It probably is easy enough to have a hidden flag but it is not what I have done in Actions.  Sorry.  I think I would prefer the option 

(3) doing --debug-dd yes
