### ISSUE TITLE
Add pragmas for SIMD

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#272]
In a pull request currently under review (#265) we are considering the possibility to include `#pragma` instructions in order to help the compiler in substituting vector instructions in some loop.

I think we should consider going by hand and adding these kind of instructions to the code in basically all the numerically expensive loops that allow it.

We should also decide which kind of `#pragma` to use. The options are:
- INTEL pragmas (e.g. `#pragma ivdep`)
- GCC pragmas (e.g. `#pragma GCC ivdep`)
- OpenMP 4.0 pragmas (e.g. `#pragma omp simd`), which in principle should be portable.

In the mentioned pull request I wrote @jpazurikova to feel free to use INTEL ones (that they tested already). However, before applying them systematically to the whole code we should pick the best choice among those three.

I would go for OpenMP 4.0 pragmas, supposedly more portable, though we should first check if they work equally well. We should test all possibilities on [our test set](https://github.com/plumed/benchmarks). Notice that some compilers (at least INTEL) does pretty well in vectorizing code even without these pragma's, so we should also check if it is worth doing it or if a simple command line option does everything.

**Comment by jpazurikova** [comment]
Yes, I would be happy to help. What time frame do you have in mind for including this? I suppose it will not make it into v2.4.

**Comment by GiovanniBussi** [comment]
Hi! I would say it's a minor change so I would be happy to include it as soon as it's done (before 2.4, or later in 2.4.x). So, if anyone is willing to make some test and report it on this thread it would be useful.

I think it would be useful to also check which other loops in the code are critical and would benefit from these pragmas

**Comment by jpazurikova** [comment]
I have looked into OpenMP 4.* and I have some good news. It seems that it would be beneficial to rewrite not only those two pragmas that gave the deprecated warning, but also #pragma ivdep which is Intel compiler dependent. It should be replaceable by #pragma omp simd safelen(x) which should enable vectorization in loops that compiler incorrectly suspects of data dependencies. This is good news because omp pragmas should be compatible also with other compilers, so we can achieve vectorization not only for icc. 

I will try and replace pragmas in the close structure method. I will run compilation tests with intel compilers (except for v18, I do not have access to that yet) and gcc. Hopefully, I will manage to get some vectorization report from gcc to verify that those loops have been indeed vectorized. 

Then, we can talk about other performance enhancement, although that is more complex topic including parallelization and memory access.

**Comment by jpazurikova** [comment]
I have rewritten the pragmas to OpenMP v4 ones and verified by optimization reports that loops have been vectorized (all with icc, some with gcc, but still better than nothinh). I am preparing the commit. What branch should I apply it on?

**Comment by GiovanniBussi** [comment]
Great!

If possible I would merge it on v2.4. Thanks!

Giovanni
