### ISSUE TITLE
Modify an Action

### ISSUE THREAD

**Issue by MoleOrbitalHybridAnalyst** [plumed/plumed2#317]
I wonder whether it is possible to modify a defined action (change ATOMS, reassign parameters, etc.) by plumed_cmd on the fly. 
What I want to do is using different settings for the same action in different time steps in my MD code.

**Comment by GiovanniBussi** [comment]
Hi,

this is currently not possible, but the code could be changed to do it.

Something that could be done in a clean way is to eliminate the last action in the list in order to replace it with something new. There is not such a cmd yet, but it's easy to add and should work well. You could then remove the last actions and replace them with new ones (with cmd("readInputLine")).

Changing an action in the middle of the list is more problematic, since you might have later actions depending on it (and thus storing pointers to the computed values).

Thus, if you want to replace a CV on which you are acting with a RESTRAINT I think there is no problem. If you want to replace a CV on which you are acting with a METAD you would be forced to do a full METAD restart every time.

Adding a cmd to remove the last action in the list is easy. In case you are interested in testing it, I can implement it on a branch (or maybe you are able to do it by yourself).

Giovanni

**Comment by MoleOrbitalHybridAnalyst** [comment]
Hi Giovanni,

Thanks a lot for your quick and helpful response!

Deleting the last action is also the first idea I came up with. What I did
is deleting the last member of the actionSet and pop_back() the vector and
then do the pilots=actionSet.select<ActionPilot*>() again. Is this all what
I need?

Best Regards,
Chenghan

**Comment by GiovanniBussi** [comment]
Yes that's correct.

Notice that the call `pilots=actionSet.select<ActionPilot*>()` is a sort of hack (I realized it now). I think the same functionality should be implemented in a cleaner way adding a sublist inside ActionSet so that it is maintained whenever an action is added or removed.

Anyway, I think you should be able to workout the thing. I close the issue now, in case you need further help just reopen it

Giovanni
