### ISSUE TITLE
Segmentation fault whenever more than 2 CVs are used for METAD with REWEIGHTING_NGRID

### ISSUE THREAD

**Issue by OleinikovasV** [plumed/plumed2#328]
PLUMED consistently breaks at a REWEIGHTING_NHILLS step whenever I run METAD with REWEIGHTING_NGRID using more than two arguments (it works fine with one and two). Does not drop any useful error messages other than "Segmentation fault".
I need this to obtain configuration weights using REWEIGHT_METAD for my simulation of METAD using 3 CVs.

**Comment by valsson** [comment]
Hello, 

I have a feeling what might be the problem. Can you do the changes shown [here](https://github.com/valsson/plumed2/commit/a81f009de1f5d2bd1656b4024cd25bbcfbae2c84), recompile and check if it works. 

Omar

**Comment by ladislav-hovan** [comment]
Hi Omar,

I was also looking at this issue, and with the changes you've suggested, the "Segmentation fault" message is replaced by "Floating point exception (core dumped)". However, I've noticed something else - on line 1862, an attempt is made to access the (i-1)th element of the rewf_grid_. The variable i starts with the value of rank, and there is no reason why it can't be zero. Indeed, if plumed is compiled without MPI, it will always be zero. This would instantly cause the segfault to happen (accessing the -1st element of the array). However, since I'm not sure about how the formula works, I am unable to fix it.

Ladislav
