### ISSUE TITLE
LAMMPS DEZ-2018 AND PLUMED

### ISSUE THREAD

**Issue by wever** [plumed/plumed2#430]
Probably there is an error integrating  LAMMPS and plumed. It works for me, but i changed one line in LAMMPS script: 
I needed to change the line 206 in $LAMMPS/lib/plumed/Install.py:
"cmd = 'echo PLUMED_LIBDIR="%s/lib" > Makefile.lammps; cat **liblink/plumed/src/lib/Plumed.inc.%s** Makefile.lammps.%s >> Makefile.lammps' % (homedir,mode,mode)"...
to:
"cmd = 'echo PLUMED_LIBDIR="%s/lib" > Makefile.lammps; cat **liblink/Plumed.inc.%s** Makefile.lammps.%s >> Makefile.lammps' % (homedir,mode,mode)"

**Comment by invemichele** [comment]
Hi @wever ,
the issue is that lammps requires plumed to be installed (`make install`) and is not meant to link with the compiled source. This was a choice of lammps maintainers, see https://github.com/lammps/lammps/pull/1228#issuecomment-442491143

You can safely use the workaround of changing line 206 or, as @PabloPiaggi suggests, get used to do `make install` every time you recompile plumed...
Regards

**Comment by GiovanniBussi** [comment]
I think this can be closed. @wever just reopen the issue if you need further clarification.
