### ISSUE TITLE
Remove python 2 support

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#502]
I would like to remove python 2 support in PLUMED 2.6. This would allow some parts of the python interface to be simplified. Please comment here if for some reason you think this is a bad idea.

**Comment by carlocamilloni** [comment]
Yes, python2 is at end of life no reason to support it anymore

**Comment by GiovanniBussi** [comment]
To be clear what I plan (for 2.6) is:
- make `./configure` only accept a python 3 executable.
- install on PyPI a cythonized c code with language_level=3.

A possible way out for people with need to use/test plumed on python 2 would be to install python wrappers with plumed 2.5 and, if needed, set `PLUMED_KERNEL` to point to plumed 2.6. My guess is that installing `py-plumed` from conda would work correctly also from python 2 (installing plumed 2.5).

I cc also people that might be interested in using plumed from python wrappers @tonigi @ceriottm @dwhswenson @stevenvdb

**Comment by dwhswenson** [comment]
This is fine for us: I agree that it should just mean that if you're using Python 2.7, you'll get PLUMED 2.5 from `conda` or `pip`. OPS will probably drop Python 2 support in early 2020.

Side note on avoiding mistakes in the process: Mainly, be sure to add [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) to the `setup.py`, and add the appropriate version constraints to the conda recipe's `meta.yaml`. If not, you get the mess where `pip`/`conda` installs Python 3-only code under Python 2.7, and you have to manually remove the release from pypi/conda-forge. I mention because I've seen others make these mistakes (especially not adding `python_requires` for `pip`-based installation!)

**Comment by ceriottm** [comment]
We are planning to upgrade i-PI to python 3, so this looks fine to me - and
timely.
Best
Michele
