### ISSUE TITLE
Issued with `gmx mdrun -rerun -plumed`

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#576]
See [this post](https://groups.google.com/d/msgid/plumed-users/0fa8e551-7461-478c-bb41-e799bf1b99b3%40googlegroups.com).

I used it in the past, so this might be a problem that appeared in some release, or specific to the employed settings. To be checked.

**Comment by wehs7661** [comment]
Hi Dr. Bussi,
I had a problem that might be related to this issue. Recently our group has been working on testing of adding alchemical variables in PLUMED. (We patched the code to GROMACS 2020.2.) We've tested 1D metadynamics biasing the alchemical variable as the CV and there was no problem. However, I later moved to 2D metadynamics that biased one conformational CV (a torsional angle) and the alchemical variable, the same error occurred: 
```
-------------------------------------------------------
Program:     gmx mdrun, version 2020.2-MODIFIEDUnknown exception:
(exception type: N4PLMD14ExceptionErrorE)+++ PLUMED error
+++ at PlumedMain.cpp:513, function virtual void PLMD::PlumedMain::cmd(const
string&, void*)
+++ assertion failed: initialized
+++ message follows +++
cmd("isEnergyNeeded") should be only used after plumed initializationFor more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors
-------------------------------------------------------
```
This also happened even if I tried to run a normal metadynamics only biasing the torsional angle (so no alchemical variables were involved). I also tried the test with unmodified PLUMED patched with GROMACS 2019.6 and GROMACS 2020.2, the former one didn't have any error, while the latter had the same error. It is also unclear to me when this error would occur, since I didn't have this error when running metadynamics biasing the alchemical variable using the modified PLUMED patched with GROMACS 2020.2. The PLUMED input file can be downloaded [here](https://drive.google.com/file/d/1J4zy2L_xFBw4sczjJTcte_uXIbuTn1m1/view?usp=sharing). Please let me know if more information is needed. Thank you!

**Comment by GiovanniBussi** [comment]
@wehs7661 please do not write the same message twice (here and on the mailing list) since it creates confusion.

As far as I can tell this might be a bug of the 2020.2 patch.

Can you upload a tpr file so as to reproduce it?

**Comment by wehs7661** [comment]
Thank you for your reply and my apologies for causing confusion! The tpr file can be downloaded here: https://drive.google.com/file/d/1ZWt8UxCjTvgJHEGpXV2Gl4GI_cqV1r2I/view?usp=sharing

**Comment by sivadasetty** [comment]
Hi,
Is this still an open issue? I noticed the same issue with `gmx mdrun -rerun -plumed` using GROMACS 2020.4 and PLUMED 2.7.0. After checking the related issue #588, I modified `plumedswitch to 0` from `plumedswitch = 1` in  legacymdrunoptions.cpp on line 179 in GROMACS 2020.4 patch, which seem to have fixed this problem. 

However,  I am not sure if this temporary fix may result in other issues. So, for now I downgraded GROMACS to 2018.6 and PLUMED to 2.5.2. These versions seem to work with `gmx mdrun -rerun -pumed`.
