### ISSUE TITLE
OpenMP parallelization of neighbor lists

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#581]
@carlocamilloni @maxbonomi  I open an issue since it is always difficult to find the comments associated to commits later.. Anyway, this discussion started at this commit: https://github.com/plumed/plumed2/commit/563e726ec74953286db89ea258eae520f4f94c42

**Comment by carlocamilloni** [comment]
let's wait for travis but locally works well, and for CVs including many atoms the scaling improvement is quite good!

**Comment by carlocamilloni** [comment]
the last remaining issue appears only with PIV+openMP+NUMERICAL_DERIVATIVES (with and without MPI), the derivatives are fine are the numerical that are wrong when using neighbour list and openMP.. @SilvioPipolo any idea? I would say that this is a piv issue, the problem is not reproducible using COORDINATION NLIST NUMERICAL DERIVATIVES and OPENMP

**Comment by carlocamilloni** [comment]
@GiovanniBussi @maxbonomi @gtribello @SilvioPipolo I think the issue is that using MPI/OpenMP the order of the pairs in the neighbour list can change after every update, I would say that this is not a problem, but in PIV the previous positions are stored and consequently these may be not comparable after neighbour list update. One simple workaround (because I would say that having parallel neighbour list is quite important) is to be able to pass a "serial" signal that switches off the parallelisation of the list and this can be used within PIV. What do you think?

**Comment by carlocamilloni** [comment]
my conclusion is that PIV is not thread-safe, anyway with the flag the test are passed (let's wait for travis ;-) ) and is also useful for debug

**Comment by carlocamilloni** [comment]
Finally passing all tests! b99ca765a13907142c7d97a5b6131fa79f1b8926
