### ISSUE TITLE
Plumed patch breaks gromacs 2020.2 install

### ISSUE THREAD

**Issue by lsmainzer** [plumed/plumed2#591]
Hello!
 I am able to install fromacs 2020.2 by itself. I am also able to git pull from the latest version of plumed v2.6 branch and install it. However, when I patch a fresh gromacs root folder with plumed, I am no longer able to install it. I am getting this error at the "make check" stage of gromacs install:

The following tests FAILED:
         43 - MdrunTests (Failed)

Unfortunately, I am new to gromacs and do not know quite what that means. Would you be able to give me a few suggestions for why plumed patch might be causing this? I am applying the patch before running the gromacs cmake command. 

Thank you very much.

**Comment by GiovanniBussi** [comment]
@lsmainzer perhaps you should disable GROMACS tests? I think there's a cmake option to do so.

**Comment by trogon44** [comment]
Hi @lsmainzer, I also received this same error. It is apparently simply due to the fact that MdrunTests is seeing unexpected additions to mdrun -h from the options added by PLUMED. See this post on the GROMACS mailing list: https://www.mail-archive.com/gromacs.org_gmx-users@maillist.sys.kth.se/msg41009.html.

**Comment by lsmainzer** [comment]
Wow, nice @trogon44 ! This is great to know! I am closing the ticket.
