### ISSUE TITLE
Metadynamics can't run using MPI threads 

### ISSUE THREAD

**Issue by aigulkhkmv** [plumed/plumed2#667]
Hello! 

I want to run metadynamics simulation on MPI threads and OpenMP threads, but can’t run simulation this way.
I have Gromacs patched with Plumed with MPI and without MPI.

When I run the simulation using gmx_mpi by command:
- `$ mpiexec -np 3 gmx_mpi mdrun -v -s dynamics.tpr -plumed plumed.dat -ntomp 5`
Simulation run using **3 MPI processes** and using 5 OpenMP threads per MPI process. But that's not what I want. By running the simulation in this way, it will take 23 days to get results. 
- `$ mpiexec -np 3 gmx_mpi mdrun -v -s dynamics.tpr -plumed plumed.dat -ntomp 1 -ntmpi 2`
I have this error: `Setting the number of thread-MPI ranks is only supported with thread-MPI and GROMACS was compiled without thread-MPI.`

When I run simulation using gmx using command:
-  `$ gmx mdrun -v -s dynamics.tpr -plumed plumed.dat -ntmpi 3 -ntomp 1”`
I have error: `you are trying to use an MPI function, but MPI is not initialized`. How can I initialize the MPI function? 
- If I run **simple MD using gmx** by command: `$ gmx mdrun -s dynamics.tpr -ntomp 3 -ntmpi 2 -v`
Everything ok, the process run using 2 MPI threads and using 3 OpenMP threads per tMPI thread.

How can I run metadynamics simulation using MPI threads? 

Thanks!

**Comment by GiovanniBussi** [comment]
PLUMED does not work with thread-MPI. thread-MPI is not a real MPI
implementation, it just covers a subset of MPI that is used within GROMACS.

If you want to reproduce the same setting that you have with this run:
  gmx mdrun -s dynamics.tpr -ntomp 3 -ntmpi 2 -v
you should:
(a) test if the following plain MD gives similar performances. It should,
otherwise there is something wrong with the way you installed or configured
MPI:
  mpiexec -np 2 gmx_mpi mdrun -s dynamics.tpr -ntomp 3 -v
(b) if that's working correctly, try adding plumed:
mpiexec -np 2 gmx_mpi mdrun -s dynamics.tpr -ntomp 3 -v -plumed plumed.dat

In your first example you are for some reason using 5 openMP threads and 3
processes, which is a completely different setup, and it's not clear why.

As a further note, knowing that the simulation would need 23 days is not
particularly interesting. Please post how many days are required with and
without plumed to have the comparison. And please also post your plumed.dat
file since it is easy to guess if there's something particularly expensive
there that can be expected to slow down your run. Finally, you should
provide more information about the system if you expect people to comment
about performance (number of atoms, type of computer, etc).

Giovanni

**Comment by aigulkhkmv** [comment]
Thank you very much, you have helped to make it more clear for me!
