### ISSUE TITLE
Add configure support for libtorch

### ISSUE THREAD

**Issue by valsson** [plumed/plumed2#678]
I see there is a branch called libtorch with commit 684b5d7 trying to add support for libtorch to the configure script. @GiovanniBussi, what is the status of this? Is it still a work in progress? 

It would be useful to add support for libtorch as it is started to be used in some plumed modules. 

I am happy to help with this as I can, including testing and such

**Comment by luigibonati** [comment]
Hi @valsson!
I am using Libtorch with PLUMED,  and I also wrote a simple interface to load serialized models trained in python as CVs (see e.g. https://www.plumed-nest.org/eggs/20/004/). 

It is relatively easy to link a specific version of libtorch, here you can find some instructions for libtorch v. 1.4 (in the last section of the notebook)
https://colab.research.google.com/drive/1dG0ohT75R-UZAFMf_cbYPNQwBaOsVaAA 

I tried with @GiovanniBussi to see whether it was possible to detect Libtorch automatically in the configure script. However, I believe that even if it is possible it is not a good option for now, as libtorch is not yet mature enough to be included in a stable version. Some issues are the following:

- The standard way to use libtorch is to link the precompiled version which works fine in most circumstances. However, this makes it harder to link PLUMED against it, as they both look for the same libraries. For instance, the precompiled version of libtorch comes with a version of lapack that is not complete, so when PLUMED looks for the latter it complains. A workaround is to use internal blas/lapack with PLUMED.

- The Pytorch C++ APIs are in beta phase, with continuous major breaking changes. In the last two years, they changed two or three times the way in which they serialize the model from Python, with no backward compatibility. This means that the interface to load models trained in Python inside PLUMED possibly needs to be updated.

- They recommend using CMake to build applications, in order to set the right library flags which might otherwise change from one version to another. 

So, while it is relatively easy to link a specific version of libtorch for development purposes, I think it is not easy to integrate into PLUMED, at least until they release a more stable version.

I'm working on writing updated instructions on how to configure PLUMED with newer versions of libtorch, I'll let you know as soon as I do.

Luigi

**Comment by valsson** [comment]
Thank you @luigibonati for the information! 

@jakryd and I are also relying heavily on libtorch in our [MRSE](https://arxiv.org/abs/2007.06377) method. We have been using our own compiled version of libtorch (not the precompiles ones) that is linked to PLUMED. 

This morning I wanted to try to compile PLUMED with a more recent precompiled version so I tried version 1.8 from the website. I remembered seeing the libtorch branch so it came to my mind to ask what is the status of adding the automatic configuration of libtorch. 

However, I see indeed the issues that you mentioned. For example, parts of the code are broken due to changes in the libtorch API. 

Also, I had to change `-std=c++11` to `-std=c++14` in the `Makefile.conf` as libtorch 1.8 requires a C++14 compiler. This might be an issue for standardizing the libtorch configure in PLUMED. 

Thus, I would agree that at the moment it is not a good option to try to detect Libtorch automatically in the configure script.

I will close the issue for now.

**Comment by GiovanniBussi** [comment]
>Also, I had to change -std=c++11 to -std=c++14 in the Makefile.conf as libtorch 1.8 requires a C++14 compiler. This might be an issue for standardizing the libtorch configure in PLUMED.

Also @maxbonomi suggested this, I am going to implement an option so as to avoid the need to manually edit the Makefile.conf file

**Comment by GiovanniBussi** [comment]
Notice: I added it for master. Can be easily backported to v2.7 if needed
