### ISSUE TITLE
Python interface with driver: WARNING: IFile closed in the middle of reading. seems strange!

### ISSUE THREAD

**Issue by Golovin-Andrey** [plumed/plumed2#682]
Dear all, I am  playing around with python bindings, the only diff in output between python script and 'plumed driver'  is this warning :
WARNING: IFile closed in the middle of reading. seems strange!
I used several READ statements to read from CV file.  
As result only one line of CV was read (Cycles 1). 
I found same warning in output in plumed nest, but still have no clue.
If needed I will provide  script but it's quite trvial, create Plumed object, create Input object , calc 
Thanks in advance

**Comment by GiovanniBussi** [comment]
Can you post an example? I mean: a zip with a short traj, a plumed input, and your python script.

**Comment by Golovin-Andrey** [comment]
Sure !  cv file can be taken from here : https://vsb.fbb.msu.ru/share/golovin/tmp/CV.0.gz 
python script :
`
import plumed

filecv = '/tmp/CV.0'
kernel = '/home/domain/data/prog-ripper/plumed-2.7.1-b-mpi/lib/libplumedKernel.so'
f = open('/tmp/1.dat' , 'w') 
with  plumed.Plumed(kernel=kernel) as p:
    p.cmd("setMDEngine","driver")    
    p.cmd('setNatoms', 0)
    p.cmd("setTimestep", 1.)
    ib=plumed.InputBuilder(toplumed = p, tofile= f, kernel=kernel)
    p.cmd("init")
    ib.READ(LABEL='cv',  FILE=filecv,IGNORE_TIME=True, IGNORE_FORCES=True, VALUES='CV')
    ib.READ(LABEL='meta',FILE=filecv,IGNORE_TIME=True, IGNORE_FORCES=True, VALUES='M.rbias')
    ib.READ(LABEL='uwa', FILE=filecv,IGNORE_TIME=True, IGNORE_FORCES=True, VALUES='UW.bias')
    ib.READ(LABEL='lwa', FILE=filecv,IGNORE_TIME=True, IGNORE_FORCES=True, VALUES='LW.bias')
    ib.REWEIGHT_METAD(LABEL='w1', TEMP=300, ARG='meta.rbias')
    ib.HISTOGRAM(LABEL='h1',ARG='cv', BANDWIDTH=0.005, GRID_BIN=50, GRID_MAX=0.4, GRID_MIN=-0.4, 
                 KERNEL='gaussian', LOGWEIGHTS='w1')
    ib.CONVERT_TO_FES(LABEL='ff',GRID='h1', MINTOZERO=True,    TEMP=300 )
    ib.DUMPGRID(GRID='ff', FILE='/tmp/fes.dat')
    ib.ENDPLUMED()
    p.cmd('calc')
f.close()
`
write to 1.dat is done is just to compare with binary:
`plumed driver  --noatoms --plumed 1.dat`

**Comment by Golovin-Andrey** [comment]
And a small question, may I pass pandas to this driver script and get fes array ?

**Comment by GiovanniBussi** [comment]
@Golovin-Andrey your script is reading a single line. The correct way to process these files would be to replace this
```python
    p.cmd('calc')
````
with this
```python
    stop=np.array((1,),dtype='int')
    p.cmd("setStopFlag",stop)
    stop[0]=0
    while(True):
        p.cmd('calc')
        if stop[0]!=0:
            break
```

Notice that there is currently a small bug in the python interface (see [here](https://github.com/plumed/plumed2/pull/653#issuecomment-734945963)). In particular, the python interface is passing pointers to long ints (64 bits) to plumed, but plumed is sometime interpreting them as normal ints (32 bits). This case ("setStopFlag") is one of these few cases. My guess is that the code above works (I tested it now) only because the first 4 bytes of a 64 bits int are equivalent to the corresponding 32 bits representation. You can see it with the following version
```python
    allstop=[]
    stop[0]=2**32 # only 4 least significant bytes are zero
    while(True):
        allstop.append(stop[0])
        p.cmd('calc')
        if stop[0]%2**32!=0: # only check 4 least significant bytes
            break
    f.close()
print(len(allstop)) # 60001
print(allstop[-2]) # 4294967296
print(allstop[-1]) # 4294967297
```

Hopefully this will be fixed in plumed 2.8. But meanwhile, the syntax I suggested above would work in spite of this bug. Once this is fixed, you will have to use
```
    stop=np.array((1,),dtype='int32')
```
instead (that currently is giving an error).

**Comment by GiovanniBussi** [comment]
> And a small question, may I pass pandas to this driver script and get fes array ?

You can write a pandas dataframe on CV.0 using `plumed.write_pandas` and then read the resulting fes with `plumed.read_as_pandas`. Plumed will anyway work using temporary files.

**Comment by Golovin-Andrey** [comment]
@GiovanniBussi  Thanks a lot, it works !  
Is it good idea to speed up plumed temp files with tmpfs in RAM ?

**Comment by GiovanniBussi** [comment]
> @GiovanniBussi Thanks a lot, it works !
> Is it good idea to speed up plumed temp files with tmpfs in RAM ?

No idea... I guess most of the time will be used anyway for formatting/unformatting, so I guess not, but I never tried.

**Comment by GiovanniBussi** [comment]
@Golovin-Andrey another comment: if you want to *pass* CVs to plumed, you can use the cmd "setExtraCV" instead of reading them with READ. See an example [here](https://github.com/plumed/plumed2/blob/e72d9ad95b9ba45ae75e0fabc078b1388c1c58b7/regtest/basic/rt-make-extracv/main.cpp#L42-L45). To use this in python, you should define `extracv` and `extracvf` as `np.zeros((1,))` (arrays with one element).
