### ISSUE TITLE
Error in recognizing TER in nucleic acid PDB files

### ISSUE THREAD

**Issue by mrjoness** [plumed/plumed2#697]
Hello,

I'm not sure if this is a well known issue, but there seems to be an indexing bug when using residue assignments for multiple nucleic acid molecules. For example, I've been working with 8-mer dsDNA with a PDB of the form:

`ATOM      1  N1   DG A   1       3.486  63.924  55.476  1.00  0.00           N`
`ATOM      2  C5'  DG A   1       3.816  62.560  63.483  1.00  0.00           C`  
`ATOM      3  C3'  DG A   1       1.496  62.026  62.388  1.00  0.00           C`
....
`ATOM    251  H2'  DC A   8       8.220  37.663  52.396  1.00  0.00           H`  
`ATOM    252 H2''  DC A   8       8.367  38.483  50.799  1.00  0.00           H`  
`ATOM    253 HO3'  DC A   8      10.277  37.418  53.464  1.00  0.00           H ` 
`TER     254       DC A   8`
`ATOM    255  C2   DG B   1       2.673  40.876  55.887  1.00  0.00           C`  
`ATOM    256  O5'  DG B   1      -4.203  42.603  58.169  1.00  0.00           O ` 
`ATOM    257  O3'  DG B   1      -1.223  44.012  61.016  1.00  0.00           O  `
....
`ATOM    505  H42  DC B   8       6.681  64.577  52.274  1.00  0.00           H  ` 
`ATOM    506  H5'  DC B   8       0.093  64.347  45.626  1.00  0.00           H `  
`ATOM    507 H5''  DC B   8       0.939  62.869  46.246  1.00  0.00           H  ` 
`TER     508       DC B   8` 

where strands are identified as A or B and the base residues are 1-8. When calculating the COM distance between two bases, one would expect the following to work in PLUMED:

`a1: COM ATOMS=@base-A1 `
`b8: COM ATOMS=@base-B8 `
`d: DISTANCE ATOMS=a1,b8 `

I have found that a1 correctly identifies the COM of A1, but each atom index in b2 is off by one (likely because it does not recognize TER which has its own index). This means that it ends up grabbing mostly backbone and phosphate atoms instead, and d=1 at equilibrium instead of the expected COM distance d=0.6. I was able to fix this and recover d=0.6 by running my own script over the PDB that accounts for this indexing mismatch. 

I would be interested to know if this is an implementation error on my part, or an issue with plumed. I am using version                   2.7.1. 

Thank you!
-Mike

**Comment by GiovanniBussi** [comment]
@mrjoness thanks for your feedback.

PLUMED reads the number from the PDB file, so in your input it will assume that the H42 of B8 (for instance) has serial number 505 (i.e., same as specifying atom number as 505 in the input). If this is what you observe, this is not a bug. We do this to allow users to provide names only for a subset of the atoms.

You should renumber your PDB so that it contains consecutive serial numbers, either with a script or using [pdbrenumber](https://www.plumed.org/doc-v2.7/user-doc/html/pdbrenumber.html). The latter has been made specifically to allow atom numbers >=100k, but works also for smaller systems. Obviously, make sure your PDB contains atoms listed in the correct order and without gaps.

**Comment by mrjoness** [comment]
Ah I see. I applied pdbrenumber as you suggested, and it made the following change from
```
TER 254 DC A 8
ATOM 255 C2 DG B 1 2.673 40.876 55.887 1.00 0.00 C
```
to 
```
TER 254 DC A 8
ATOM 254 C2 DG B 1 2.673 40.876 55.887 1.00 0.00 C
```
This fixes the problem I was having. Thank you!
