### ISSUE TITLE
Plumed 2.8 support for gromacs 2022.1

### ISSUE THREAD

**Issue by dipietrantonio** [plumed/plumed2#822]
Dear all,
[on your documentation ](https://www.plumed.org/doc-v2.8/user-doc/html/_installation.html#Patching)it is stated that gromacs-2022.1 is in the list of supported MD engines. But `plumed patch -l` output states differently
```
plumed patch -l
PLUMED patching tool

Available MD engines:
  gromacs-2019.6
  gromacs-2020.6
  gromacs-2021.4
  gromacs-4.5.7
  namd-2.12
  namd-2.13
  namd-2.14
  qespresso-5.0.2
  qespresso-6.2
```
Is this an issue with the documentation of with the software?

Cheers
Cristian

**Comment by GiovanniBussi** [comment]
Hi,

this is due to the way we generate manuals and release patches.

On GitHub, we have (among others) the following maintenance branches: v2.7 v2.8
We also have the following tags: v2.7.0 v2.7.1 ... v2.8.0, which are snapshots along those branches.

The online manual is created with the tip of the branch (e.g. v2.8). It might thus document some code that is not yet in a published version but will appear soon. Usually we only add minor fixes along maintenance branches, but in this case we added a patch for gromacs 2022.

Notice that patches are largely portably across different plumed versions. And notice that you can safely use the tip of branch v2.8. Thus you have two options:
- download branch v2.8 from the GitHub repository and copy `patches/gromacs-2022.1*` in the `patches` directory of you plumed source code
- download branch v2.8 from the GitHub repository and compile that version

Hope this helps

Goivanni

**Comment by dipietrantonio** [comment]
Thanks Giovanni, we can close this issue now.
