### ISSUE TITLE
gromacs 2022

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#865]
I have uploaded a new gmx2022.2 patch, this needs some testing but should work better than the former, testing and feedbacks are welcomed (@andreashlarsen)

**Comment by andreashlarsen** [comment]
thank you, @carlocamilloni

**Comment by GiovanniBussi** [comment]
@carlocamilloni I tested `-hrex` in order to port #831 also to gromacs 2022. The fix avoids the deadlock, and so it should be included (I added it already). However, `-hrex` seems not to work correctly (acceptance is always 1.0).

I am not sure I have time to fix it soon. Should we disable with an error perhaps in the patch for 2022?

**Comment by carlocamilloni** [comment]
@GiovanniBussi Does the fix worked?
