### ISSUE TITLE
GitHub Actions: split linux-doc-mpi to avoid running regrets

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#898]
Right now this is by far the slowest action, I think it may be better to have split into two different action
-mpi- 
-doc-mpi

where the latter does not execute the regtest suite to decrease the running time. 
Actually do we actually need the case -mpi-? Isn't this already covered by -coverage-mpi? @GiovanniBussi

**Comment by GiovanniBussi** [comment]
@carlocamilloni I think this is because of the new manual building which is very slow. It makes sense to split them indeed.

Regarding the separate coverage build, the reason to keep both is that the coverage build is configured with `-O` (otherwise I think it does not work correctly), whereas plumed by default sets `-O3`, which is what most users would use, then I thought it can be useful in case there is some subtle bug appearing when we optimize.

As a side note, I have a long-standing unfinished work to allow removing the -mpi- cases (it's actually a trick to compile a single executable and then load mpi a posteriori), I will try to see if I manage to merge it before the end of the month
