### ISSUE TITLE
Get all components in Q6

### ISSUE THREAD

**Issue by thangckt** [plumed/plumed2#899]
Dear Developers, 

I wonder if there is a way to access all components in Multicolvar? Like something has been discussed in #266 
As explained by @gtribello, there is a way to use DUMPMULTICOLVAR

But I want to use the components of Multicolvar in a biased calculation.
So there is any progress so far? Or can you have a little guide on how to obtain this?

Thank you so much

**Comment by gtribello** [comment]
Hello

There is no way to do this with the master version of the branch.  I am working (slowly) to make it possible in another branch so you could try working with this branch rather than master.  If that is of interest then you can get the code by doing:

git clone https://github.com/plumed/plumed2.git
git checkout hack-the-tree

In this new version of the code the components of actions can be scalars, vectors, matrices and grids.  You can thus write:

d1: DISTANCE ATOMS1=1,2 ATOMS2=3,4 ATOMS3=5,6

The object that you reference when you use the symbol d1 later in the input file is a three component vector that contains the three distances.   So 

PRINT ARG=d1 FILE=colvar

would print 3 numbers rather than one.

Now to work with Q6 you do:

q6: Q6 SPECIES=1-64 SWITCH={RATIONAL R_0=0.1}

This creates a 64 component vector called q6 that you can refer to later in your input file.

I hope that helps you get started.  If you email me (Gareth Tribello) and tell me more about what you are trying to do I can help you get started a bit better as the development branch that I am pointing you to is not very well documented.  We could perhaps have a chat on Zoom.

I hope this helps
Gareth
