### ISSUE TITLE
Normalization of SAXS scattering curve

### ISSUE THREAD

**Issue by hmcezar** [plumed/plumed2#948]
In PLUMED 2.8 we had a normalization wrt the experimental intensity:

https://github.com/plumed/plumed2/blob/005a383a299c1e4df6b7c03486971dc625900f5d/src/isdb/SAXS.cpp#L281

This is not the case in PLUMED 2.9, where the normalization is different and the use of the SCALE keyword is also different. See
https://github.com/plumed/plumed2/blob/8e4baead8ce0af86aa8eb636fb55a8fc83c6cde2/src/isdb/SAXS.cpp#L571
and
https://github.com/plumed/plumed2/blob/8e4baead8ce0af86aa8eb636fb55a8fc83c6cde2/src/isdb/SAXS.cpp#L599

This is not mentioned in the changelog, and since results can be different, I think it's worth mentioning the changes make results not backward compatible.

Also, if I may ask, are there any reasons for this change?

**Comment by carlocamilloni** [comment]
Hi @hmcezar yes we should have mentioned it, I'am amending the changelog soon. About the rationale, the normalisation with respect to the data was suboptimal because it was never at q=0, second now we have implemented method with solvent layer corrections that makes this choice even less good. In the end the only reasonable normalisation is to set the intensity to 1 and scale it if needed.
