### ISSUE TITLE
INTEL compiler not working on GH Actions

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#976]
There seems to be an issue with the certificate from INTEL.

I will temporarily disable the test and leave this issue open as a reminder

**Comment by Miniland1333** [comment]
Have you checked recently if this issue has fixed itself?

If this issue hasn't already resolved itself, one thing you may want to do is tweak the key process slightly so it always pulls the most recent key instead of the 2023-specific key. This would involve modifying the following lines
https://github.com/plumed/plumed2/blob/029d5211f4ac0cea22583dc203df44a5b3bd4da9/.github/workflows/ci.yml#L105-L107

to
```console
wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
```

Lastly, since you are using the Intel OpenAPI would it be possible to please also test `icpx` as part of the intel test? The intel classic compilers (`icc` and `icpc`) are both deprecated and will be removed at the end of the year, so it would be good to check that `icpx` is working for plumed. Thanks!

**Comment by Miniland1333** [comment]
For `icpx` specifically, there is a possibility you may need to add the CXXFLAGS `-qopenmp` or `-fiopenmp` instead of the traditional `-fopenmp` for it to link properly.

**Comment by carlocamilloni** [comment]
I am testing this
```
wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
```
and it works (branch test_intel), thanks!
I will now try to switch it to the `icpx` compiler.

**Comment by carlocamilloni** [comment]
cf #990 where the new compilers work well to build plumed but we have multiple regtest failing not only for numerical issues.

**Comment by Miniland1333** [comment]
Thank you all for addressing this so quickly!
